### ISSUE TITLE
Functions not exported in ReleaseDLL configuration

### ISSUE THREAD

**Issue by ashikns** [ShiftMediaProject/opus#1]
`OPUS_BUILD` and `DLL_EXPORT` symbols are not defined in the ReleaseDLL configuration (neither in others). This causes the project not to produce a .lib file and in turn causes the FFmpeg project build to fail since it can't find **opus.lib**.

Relevant code can be found at `opus_defines.h, line 66`. Tested using VS2017RC, I retargeted the sdk versions to Win10, 14393.

I'm building this for the first time, sorry if this is something stupid :)

**Comment by Sibras** [comment]
The DLL_EXPORT define was added in the last 1.1.3 update and seems to have been missed during the merge. It wasnt picked up on my end because VS wasnt cleaning the .lib from from the previous version and was just using that when i tested DLL builds. Adding a fix now.
